import React,{useState,useEffect} from 'react'; import {createRoot} from 'react-dom/client'; import axios from 'axios'; import './style.css';
const API='http://localhost:8080/api';
const api=axios.create({baseURL:API}); api.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization='Bearer '+t;return c;});
function Login({onLogin}){const [email,setEmail]=useState('citizen@test.com'),[password,setPassword]=useState('1234'),[msg,setMsg]=useState('');
 const submit=async e=>{e.preventDefault();try{const r=await axios.post(API+'/auth/login',{email,password});localStorage.setItem('token',r.data.token);localStorage.setItem('role',r.data.role);localStorage.setItem('name',r.data.name);onLogin(r.data.role)}catch(x){setMsg('Login failed')}};
 return <div className="center"><form className="card login" onSubmit={submit}><h1>Digital Queue</h1><p>Government Office Queue Management</p><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button>Login</button><small>Demo: citizen@test.com / staff@test.com / admin@test.com — password: 1234</small>{msg&&<b>{msg}</b>}</form></div>}
function Nav({logout}){return <nav><b>🏛 Digital Queue</b><button onClick={logout}>Logout</button></nav>}
function Citizen(){const [services,setServices]=useState([]),[sid,setSid]=useState(''),[priority,setPriority]=useState('NORMAL'),[mine,setMine]=useState([]),[result,setResult]=useState(null);
 const load=async()=>{setServices((await axios.get(API+'/services')).data);setMine((await api.get('/queue/my')).data)};useEffect(()=>{load()},[]);
 const get=async()=>{const r=await api.post('/queue/token',{serviceId:Number(sid),priority});setResult(r.data);load()};
 return <><Nav logout={()=>{localStorage.clear();location.reload()}}/><main><h2>Citizen Dashboard</h2><div className="grid"><section className="card"><h3>Get a Token</h3><select value={sid} onChange={e=>setSid(e.target.value)}><option value="">Select service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name} ({s.averageMinutes} min)</option>)}</select><div className="radio"><label><input type="radio" checked={priority==='NORMAL'} onChange={()=>setPriority('NORMAL')}/> Normal</label><label><input type="radio" checked={priority==='PRIORITY'} onChange={()=>setPriority('PRIORITY')}/> Priority</label></div><button disabled={!sid} onClick={get}>Generate Token</button>{result&&<div className="ticket"><h1>{result.tokenNumber}</h1><p>People waiting: {result.position}</p><p>Estimated wait: {result.estimatedWait} min</p></div>}</section><section className="card"><h3>My Tokens</h3>{mine.map(t=><div className="row" key={t.id}><b>{t.tokenNumber}</b><span>{t.status}</span></div>)}</section></div></main></>}
function Staff(){const [services,setServices]=useState([]),[sid,setSid]=useState(''),[counters,setCounters]=useState([]),[current,setCurrent]=useState(null),[queue,setQueue]=useState([]);
 const load=async()=>{setServices((await axios.get(API+'/services')).data);setCounters((await api.get('/queue/counters')).data);if(sid)setQueue((await api.get('/queue/service/'+sid)).data.tokens)};useEffect(()=>{load()},[sid]);
 const next=async()=>{const c=counters.find(x=>x.serviceId===Number(sid)&&x.active);if(!c)return alert('No active counter');setCurrent((await api.post('/queue/next',{serviceId:Number(sid),counterId:c.id})).data);load()};
 return <><Nav logout={()=>{localStorage.clear();location.reload()}}/><main><h2>Staff Dashboard</h2><div className="card"><select value={sid} onChange={e=>setSid(e.target.value)}><option value="">Select service</option>{services.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button onClick={next} disabled={!sid}>Call Next Token</button>{current&&<div className="ticket"><h1>Now Serving: {current.tokenNumber}</h1><button onClick={async()=>{await api.post('/queue/'+current.id+'/complete');setCurrent(null);load()}}>Complete</button><button onClick={async()=>{await api.post('/queue/'+current.id+'/skip');setCurrent(null);load()}}>Skip</button></div>}</div><div className="card"><h3>Waiting Queue</h3>{queue.map(t=><div className="row" key={t.id}><b>{t.tokenNumber}</b><span>{t.priority}</span></div>)}</div></main></>}
function Admin(){const [data,setData]=useState(null);const load=async()=>setData((await api.get('/admin/dashboard')).data);useEffect(()=>{load()},[]);if(!data)return <><Nav logout={()=>{localStorage.clear();location.reload()}}/><main>Loading...</main></>;return <><Nav logout={()=>{localStorage.clear();location.reload()}}/><main><h2>Admin Dashboard</h2><div className="stats"><div>Total Tokens<strong>{data.totalTokens}</strong></div><div>Waiting<strong>{data.waitingTokens}</strong></div><div>Counters<strong>{data.counters.length}</strong></div></div><div className="card"><h3>Counter Allocation</h3>{data.counters.map(c=><div className="row" key={c.id}><b>Counter {c.counterNumber}</b><span>{c.active?'ACTIVE':'INACTIVE'}</span><button onClick={async()=>{await api.post('/admin/counter/'+c.id+'/toggle');load()}}>Toggle</button></div>)}</div></main></>}
function App(){const [role,setRole]=useState(localStorage.getItem('role'));if(!role)return <Login onLogin={setRole}/>;return role==='CITIZEN'?<Citizen/>:role==='STAFF'?<Staff/>:<Admin/>}
createRoot(document.getElementById('root')).render(<App/>);
